name: Build and Deploy React App

on:
  push:
    branches:
      - main   # 👈 change to "master" if your repo uses master

permissions:
  contents: write   # 👈 allow pushing to deploy branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: build

