name: Build and Deploy React App

on:
  push:
    branches:
      - main   # or "master" depending on your repo

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # try 16 if 18 fails

      - name: Install Dependencies
        run: |
          npm install

      - name: Build React App
        run: |
          CI=false npm run build   # 👈 avoids React build warnings breaking CI

      - name: Deploy to GitHub Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: build


